# Generated by Django 4.2.15 on 2024-08-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("explanation", models.TextField()),
                ("url", models.URLField()),
                ("media_type", models.CharField(max_length=10)),
            ],
        ),
    ]
